//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatMessage()
        {
            this.ChatMessages1 = new HashSet<ChatMessage>();
        }
    
        public int MessageID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string Content { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
        public Nullable<int> ReplyToID { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessage> ChatMessages1 { get; set; }
        public virtual ChatMessage ChatMessage1 { get; set; }
    }
}
