//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketImage
    {
        public int ImageID { get; set; }
        public Nullable<int> PostID { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual MarketPost MarketPost { get; set; }
    }
}
