//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentConnect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDMUEcoSystemEntities : DbContext
    {
        public TDMUEcoSystemEntities()
            : base("name=TDMUEcoSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<ChatParticipant> ChatParticipants { get; set; }
        public virtual DbSet<ChatRoom> ChatRooms { get; set; }
        public virtual DbSet<ConnectCategory> ConnectCategories { get; set; }
        public virtual DbSet<ConnectPost> ConnectPosts { get; set; }
        public virtual DbSet<MarketCategory> MarketCategories { get; set; }
        public virtual DbSet<MarketChatRoom> MarketChatRooms { get; set; }
        public virtual DbSet<MarketImage> MarketImages { get; set; }
        public virtual DbSet<MarketPost> MarketPosts { get; set; }
        public virtual DbSet<MarketWishlist> MarketWishlists { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    }
}
