//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostMedia
    {
        public int MediaID { get; set; }
        public int PostID { get; set; }
        public string MediaUrl { get; set; }
        public string MediaType { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
