//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryView
    {
        public int ViewID { get; set; }
        public int StoryID { get; set; }
        public int ViewerID { get; set; }
        public Nullable<System.DateTime> ViewedAt { get; set; }
    
        public virtual Story Story { get; set; }
        public virtual User User { get; set; }
    }
}
