//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int ProfileID { get; set; }
        public int UserID { get; set; }
        public string CoverPhoto { get; set; }
        public string Bio { get; set; }
        public string Faculty { get; set; }
        public string Major { get; set; }
        public Nullable<int> StudentYear { get; set; }
        public string Hometown { get; set; }
    
        public virtual User User { get; set; }
    }
}
